project_id = "rmgtjzeuhckqhuwwzrlm"

[functions.process-query]
verify_jwt = false

[functions.find-category-schemes]
verify_jwt = false

[functions.find-startup-programs]
verify_jwt = false

[functions.generate-eligibility-quiz]
verify_jwt = false

[functions.find-nearest-csc]
verify_jwt = false

[functions.translate-content]
verify_jwt = false

[functions.generate-audio-summary]
verify_jwt = false